var constants = {
    ACTION_SET_MODE: "ACTION_SET_MODE",
    ACTION_START: "ACTION_START",
    ACTION_PAUSE: "ACTION_PAUSE",
    ACTION_RESET: "ACTION_RESET",

    STATE_RUNNING: "STATE_RUNNING",
    STATE_PAUSED: "STATE_PAUSED",

    MODE_POMODORO: "MODE_POMODORO",
    MODE_SHORT_BREAK: "MODE_SHORT_BREAK",
    MODE_LONG_BREAK: "MODE_LONG_BREAK",

    DISPATCH_SOURCE_VIEW: "DISPATCH_SOURCE_VIEW",
    DISPATCH_SOURCE_SERVER: "DISPATCH_SOURCE_SERVER",

    // Intervals, 25 min, 5 min and 10 min
    INTERVAL_POMODORO: 25 * 60,
    INTERVAL_SHORT_BREAK: 5 * 60,
    INTERVAL_LONG_BREAK: 10 * 60
};

module.exports = constants;