var constants = {
    ACTION_SET_MODE: "ACTION_SET_MODE",

    STATE_STOPPED: "STATE_STOPPED",
    STATE_RUNNING: "STATE_RUNNING",
    STATE_PAUSED: "STATE_PAUSED",

    MODE_POMODORO: "MODE_POMODORO",
    MODE_SHORT_BREAK: "MODE_SHORT_BREAK",
    MODE_LONG_BREAK: "MODE_LONG_BREAK",

    DISPATCH_SOURCE_VIEW: "DISPATCH_SOURCE_VIEW",
    DISPATCH_SOURCE_SERVER: "DISPATCH_SOURCE_SERVER"

};

module.exports = constants;